name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CloneKronOS
      run: git clone https://github.com/vvaucoul/KronOS && cp -r KronOS/* ../ ; cd ../KronOS && git checkout work-in-progress && cd -
    - name: workflow_test
      run: cd scripts && sh HephaistosGithubWorkflow.sh && cd -
    - name: InstallDependencies
      run: make -C  ../. install-dependencies
    - name: make
      run: make
    - name: Test
      run: timeout 30s make run-disk 