name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CloneKronOS
      run: git clone https://github.com/vvaucoul/KronOS . && cp KronOS/* ../
    - name: make
      run: make
  
